apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-backend.fullname" . }}
  labels:
    {{- include "ai-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ai-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ai-backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "ai-backend.fullname" . }}-db
                  key: url
